apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      containers:
        - image: gcr.io/aboverio/web:latest
          name: web
          ports:
            - containerPort: 80
              name: web
