version: 2.1

orbs:
  gke: circleci/gcp-gke@1.4.0
  gcr: circleci/gcp-gcr@0.14.1

jobs:
  docker:
    description: Docker Build & Push
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: web
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: web
          tag: $CIRCLE_SHA1

  kubernetes:
    description: Deploy to Google Kubernetes Engine
    machine: true
    steps:
      - gke/install
      - gke/rollout-image:
          cluster: default
          container: web
          deployment: web
          image: gcr.io/aboverio/web:$CIRCLE_SHA1

workflows:
  deployment:
    jobs:
      - docker:
          context: default
          filters:
            branches:
              only: main
      - kubernetes:
          context: default
          requires:
            - docker
          filters:
            branches:
              only: main
