version: 2.1

orbs:
  node: circleci/node@5.0.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gcr: circleci/gcp-gcr@0.14.1

jobs:
  install:
    description: Install Dependencies
    machine: true
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
          with-cache: true

  docker:
    description: Docker Build & Push
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: web
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: web
          tag: latest

  deploy:
    description: Deploy to Google Kubernetes Engine
    machine: true
    steps:
      - gke/publish-and-rollout-image:
          cluster: default
          container: web
          deployment: web
          image: web
          tag: $CIRCLE_SHA1

workflows:
  deployment:
    jobs:
      - install
      - docker:
          requires:
            - build
      - deploy:
          requires:
            - docker
          filters:
            branches:
              only: main
