version: 2.1

orbs:
  node: circleci/node@5.0.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gcr: circleci/gcp-gcr@0.14.1

jobs:
  install:
    description: Install Dependencies
    machine: true
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
  docker:
    description: Docker Build & Push
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: web
          tag: latest
      - gcr/push-image:
          image: web
          tag: latest

  deploy:
    description: Deploy to Google Kubernetes Engine
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: default
          container: web
          image: gcr.io/aboverio/web:latest

workflows:
  deployment:
    jobs:
      - install
      - docker:
          requires:
            - build
      - deploy:
          requires:
            - docker
          filters:
            branches:
              only: main
