version: 2.1

orbs:
  gke: circleci/gcp-gke@2.3.0
  gcr: circleci/gcp-gcr@0.16.8

jobs:
  docker:
    description: Docker Build & Push
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: web
          tag: latest
      - gcr/push-image:
          image: web
          tag: latest

  kubernetes:
    description: Deploy to Google Kubernetes Engine
    machine: true
    steps:
      - gke/update-kubeconfig-with-credentials:
          cluster: default --zone=$GOOGLE_COMPUTE_ZONE
          install-kubectl: true
          perform-login: true
      - gke/rollout-image:
          cluster: default --zone=$GOOGLE_COMPUTE_ZONE
          container: web
          deployment: web
          image: gcr.io/aboverio/web
          tag: latest

workflows:
  deployment:
    jobs:
      - docker:
          context: default
          filters:
            branches:
              only: main
      - kubernetes:
          context: default
          requires:
            - docker
          filters:
            branches:
              only: main
